'use client';
import { useState,useEffect } from 'react';
import Link from 'next/link';
import { usePathname,useRouter } from 'next/navigation';
import { MessageCircle, CircleDot, Users, Settings2, LogOut, Shield } from 'lucide-react';
import { useApp } from '@/stores/use-app';
import { Avatar,Loading,LogoMark,Modal } from '@/components/shared/ui';
const nav=[{href:'/chats',label:'Chats',icon:MessageCircle},{href:'/status',label:'Status',icon:CircleDot},{href:'/contacts',label:'Contacts',icon:Users}];
export function Shell({children}:{children:React.ReactNode}){const {me,services,preferences}=useApp();const pathname=usePathname();const router=useRouter();const [logout,setLogout]=useState(false);useEffect(()=>{if(!me)router.replace('/login')},[me,router]);useEffect(()=>{document.documentElement.dataset.theme=preferences.appearance;return()=>{delete document.documentElement.dataset.theme}},[preferences.appearance]);if(!me)return <Loading/>;return <main className={`app-shell ${preferences.compact?'compact':''}`}><aside className="rail"><Link href="/chats" aria-label="SYORA home" className="rail-brand"><LogoMark/></Link><nav>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className={`rail-link ${pathname===href?'active':''}`} title={label} aria-label={label} aria-current={pathname===href?'page':undefined}><Icon size={23}/><span>{label}</span></Link>)}</nav><div className="rail-bottom"><Link href="/settings" title="Settings" aria-label="Settings" className={`rail-link ${pathname==='/settings'?'active':''}`}><Settings2 size={22}/><span>Settings</span></Link><button className="rail-link logout-link" title="Log out" aria-label="Log out" onClick={()=>setLogout(true)}><LogOut size={21}/></button><Link href="/profile" title="Your profile" aria-label="Your profile" className={`profile-link ${pathname==='/profile'?'active':''}`}><Avatar user={me} size="small"/></Link></div></aside><div className="app-content">{children}</div>{logout&&<Modal title="Leave your space?" onClose={()=>setLogout(false)}><p className="modal-copy">You can sign back into your preview profile while this page remains open.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setLogout(false)}>Stay here</button><button className="button primary" onClick={()=>{services.logout();router.push('/login')}}>Log out</button></div></Modal>}</main>}
export function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</header>}
export function PreviewNote(){return <div className="preview-note"><Shield size={14}/><span>Frontend preview · Local demo data</span></div>}

