'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Eye, EyeOff, Feather, LoaderCircle, MessageCircle, Users } from 'lucide-react';
import { Brand } from '@/components/shared/ui';
import { useApp } from '@/stores/use-app';
export function AuthScreen({mode}:{mode:'login'|'register'|'forgot'}){
 const router=useRouter();const {services,me,sessionReady}=useApp();const [show,setShow]=useState<Record<string,boolean>>({});const [values,setValues]=useState<Record<string,string>>({});const [errors,setErrors]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const register=mode==='register';const forgot=mode==='forgot';const demoEnabled=process.env.NEXT_PUBLIC_ENABLE_DEMO==='true';
 useEffect(()=>{if(sessionReady&&me)router.replace('/chats')},[sessionReady,me,router]);
 async function submit(e:React.FormEvent){e.preventDefault();const errs:Record<string,string>={};if(!/^\S+@\S+\.\S+$/.test(values.email||''))errs.email='Enter a valid email address.';if(!forgot&&(values.password||'').length<8)errs.password='Use at least 8 characters.';if(register&&!values.name?.trim())errs.name='Enter your display name.';if(register&&values.confirm!==values.password)errs.confirm='Passwords do not match.';setErrors(errs);if(Object.keys(errs).length)return;setBusy(true);setNotice('');try{if(forgot){setNotice('Password reset is not available yet.');return}if(register)await services.register(values.name,values.email,values.password);else await services.login(values.email,values.password);router.push('/chats')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 async function demo(){setBusy(true);setNotice('');try{await services.enterDemo();router.push('/chats')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 const password=(name:string,label:string)=><label className="field">{label}<span className="input-wrap"><input type={show[name]?'text':'password'} value={values[name]||''} onChange={e=>setValues({...values,[name]:e.target.value})} autoComplete={name==='password'?'current-password':'new-password'}/><button type="button" className="password-toggle" aria-label={`${show[name]?'Hide':'Show'} ${label.toLowerCase()}`} onClick={()=>setShow({...show,[name]:!show[name]})}>{show[name]?<EyeOff size={18}/>:<Eye size={18}/>}</button></span>{errors[name]&&<small className="field-error">{errors[name]}</small>}</label>;
 return <main className="auth-page"><section className="auth-story"><Brand/><div className="auth-copy"><span className="eyebrow">A LITTLE CLOSER. A LITTLE QUIETER.</span><h1>Your people.<br/>Your own <em>space.</em></h1><p>Private conversations.<br/>Real connection.</p><div className="auth-notes"><span><MessageCircle size={18}/> Conversations that matter</span><span><Users size={18}/> A circle you choose</span><span><Feather size={18}/> Room to be yourself</span></div></div><span className="auth-foot">Thoughtfully made for your inner circle.</span></section><section className="auth-form-wrap"><div className="auth-mobile-brand"><Brand/></div><div className="auth-form">{forgot&&<Link href="/login" className="icon-button" aria-label="Back to login"><ArrowLeft/></Link>}<span className="eyebrow">WELCOME TO SYORA</span><h2>{register?'Make yourself at home.':forgot?'Find your way back.':'Good to have you here.'}</h2><p>{register?'A new space for you and your people.':forgot?'Password recovery is not currently available.':'Sign in to continue to your conversations.'}</p><form onSubmit={submit}>{register&&<label className="field">Display name<input value={values.name||''} onChange={e=>setValues({...values,name:e.target.value})} autoComplete="name"/>{errors.name&&<small className="field-error">{errors.name}</small>}</label>}{!forgot&&<label className="field">Email<input type="email" value={values.email||''} onChange={e=>setValues({...values,email:e.target.value})} autoComplete="email"/>{errors.email&&<small className="field-error">{errors.email}</small>}</label>}{!forgot&&password('password','Password')} {register&&password('confirm','Confirm password')}{!register&&!forgot&&<button type="button" className="forgot-link" onClick={()=>setNotice('Password recovery is not currently available.')}>Forgot password?</button>}{notice&&<p className="notice" role="status">{notice}</p>}{!forgot&&<button className="button primary full" disabled={busy || !sessionReady}>{busy&&<LoaderCircle className="spin" size={17}/>} {register?'Create account':'Sign in'}</button>}</form>{!forgot&&<p className="auth-switch">{register?'Already have an account?':'New to SYORA?'} <Link href={register?'/login':'/register'}>{register?'Sign in':'Create account'}</Link></p>}{demoEnabled&&<><div className="divider"><span>or take a look around</span></div><button className="button secondary full" onClick={demo} disabled={busy || !sessionReady}>Explore the demo <ArrowRight size={17}/></button></>}<p className="demo-disclosure">Protected by a short-lived session and a secure rotating sign-in cookie.</p></div></section></main>
}
