'use client';
import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Eye, Plus, Trash2 } from 'lucide-react';
import { useApp } from '@/stores/use-app';
import { Avatar, Empty, IconButton, Modal, relative } from '@/components/shared/ui';
import { MobileScreenHeader, PageHeader, PreviewNote } from '@/components/shell';
import { AttachmentContent, FilePicker } from '@/components/media/attachment';
import type { Attachment } from '@/types';

export function Status(){
 const {me,users,statuses,services}=useApp(); const [active,setActive]=useState<number|null>(null); const [creating,setCreating]=useState(false); const [text,setText]=useState(''); const [color,setColor]=useState('#4c3f66'); const [attachment,setAttachment]=useState<Attachment>(); const [error,setError]=useState('');
 const mine=statuses.filter(s=>s.userId===me!.id); const friends=statuses.filter(s=>s.userId!==me!.id); const recent=friends.filter(s=>!s.viewedBy.includes(me!.id)); const viewed=friends.filter(s=>s.viewedBy.includes(me!.id));
 function closeCreate(){if(attachment?.url.startsWith('blob:'))URL.revokeObjectURL(attachment.url);setAttachment(undefined);setText('');setCreating(false)}
 async function publish(){try{await services.publish(text,color,attachment);setAttachment(undefined);setText('');setCreating(false)}catch(e){setError((e as Error).message)}}
 return <div className="page-view"><MobileScreenHeader title="Status" action={<IconButton label="Add status" onClick={()=>setCreating(true)}><Plus size={20}/></IconButton>}/><PageHeader eyebrow="MOMENTS" title="Status" description="Share a photo, video, or thought. Statuses expire after 24 hours." action={<button className="button primary" onClick={()=>setCreating(true)}><Plus size={18}/> Add status</button>}/>
  {error&&<p className="inline-error" role="alert">{error}</p>}
  <section><h2 className="section-heading">My Status <span>{mine.length}</span></h2>{mine.length?<div className="status-grid">{mine.map((status,i)=><StatusCard key={status.id} status={status} user={me!} onOpen={()=>setActive(statuses.indexOf(status))} onDelete={()=>void services.removeStatus(status.id).catch(e=>setError((e as Error).message))}/>)}</div>:<Empty title="Share a moment" description="Add a text, photo, or video status for your friends."/>}</section>
  <section><h2 className="section-heading">Recent updates <span>{recent.length}</span></h2>{recent.length?<div className="status-grid">{recent.map(status=>{const user=users.find(u=>u.id===status.userId)!;return <StatusCard key={status.id} status={status} user={user} onOpen={()=>{void services.view(status.id).catch(e=>setError((e as Error).message));setActive(statuses.indexOf(status))}}/>})}</div>:<Empty title="Nothing new yet" description="Friend updates will appear here."/>}</section>{viewed.length>0&&<section><h2 className="section-heading">Viewed updates <span>{viewed.length}</span></h2><div className="status-grid">{viewed.map(status=>{const user=users.find(u=>u.id===status.userId)!;return <StatusCard key={status.id} status={status} user={user} onOpen={()=>setActive(statuses.indexOf(status))}/>})}</div></section>}<PreviewNote/>
  {creating&&<Modal title="Create status" className="mobile-sheet" onClose={closeCreate}><div className="status-compose" style={{background:color}}>{attachment?<AttachmentContent attachment={attachment}/>:<p>{text||'Your thought goes here.'}</p>}</div><label className="field">Text<textarea aria-label="Status text" maxLength={500} value={text} onChange={e=>setText(e.target.value)} placeholder="What’s on your mind?"/></label><div className="status-tools"><FilePicker mediaOnly onSelect={setAttachment} onError={setError}/>{['#4c3f66','#31525a','#5b3d45','#594a35','#334c42'].map(c=><button type="button" key={c} aria-label={`Use ${c} background`} aria-pressed={color===c} className="color-choice" style={{background:c}} onClick={()=>setColor(c)}/>)}</div><p className="demo-disclosure">Your status will be visible according to your privacy settings for 24 hours.</p><div className="modal-actions"><button className="button secondary" onClick={closeCreate}>Cancel</button><button className="button primary" onClick={publish}>Share status</button></div></Modal>}
  {active!==null&&statuses[active]&&<StatusViewer index={active} total={statuses.length} status={statuses[active]} user={users.find(u=>u.id===statuses[active].userId)!} onClose={()=>setActive(null)} onMove={step=>setActive((active+step+statuses.length)%statuses.length)}/>} </div>;
}
function StatusCard({status,user,onOpen,onDelete}:{status:import('@/types').StatusPost;user:import('@/types').User;onOpen:()=>void;onDelete?:()=>void}){return <article className="status-card"><button className="status-open" onClick={onOpen} aria-label={`View ${user.name}'s status`}><span className="status-ring"><Avatar user={user}/></span><span><strong>{user.id==='demo'?'My Status':user.name}</strong><small>{relative(status.createdAt)}</small><p>{status.text||status.attachment?.name}</p></span></button>{onDelete&&<IconButton label="Delete status" onClick={onDelete}><Trash2 size={17}/></IconButton>}</article>}
function StatusViewer({status,user,index,total,onClose,onMove}:{status:import('@/types').StatusPost;user:import('@/types').User;index:number;total:number;onClose:()=>void;onMove:(step:number)=>void}){useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')onMove(-1);if(e.key==='ArrowRight')onMove(1)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[onMove]);return <Modal title={`${user.name}'s status`} wide className="status-viewer-dialog" onClose={onClose}><div className="status-progress" aria-label={`Status ${index+1} of ${total}`}>{Array.from({length:total},(_,i)=><span key={i} className={i<=index?'complete':''}/>)}</div><div className="viewer-person"><Avatar user={user} size="small"/><span><strong>{user.name}</strong><small>{relative(status.createdAt)}</small></span></div><div className="status-viewer" style={{background:status.color}}>{status.attachment?<AttachmentContent attachment={status.attachment}/>:<p>{status.text}</p>}</div><div className="viewer-controls"><IconButton label="Previous status" onClick={()=>onMove(-1)}><ChevronLeft/></IconButton><span>{index+1} / {total}</span><IconButton label="Next status" onClick={()=>onMove(1)}><ChevronRight/></IconButton></div></Modal>}
